### ISSUE TITLE
cargo build failed

### ISSUE THREAD

**Issue by tony2u** [marc2332/deno_tauri#1]
**RUST Environment:**
(base) H:\deno_tauri>rustup toolchain list
stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

**Build in stable:**
(base) H:\deno_tauri>cargo build
    Blocking waiting for file lock on package cache
   Compiling runtime v0.1.0 (H:\deno_tauri\runtime)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> runtime\src\main.rs:1:12
  |
1 | #![feature(map_try_insert)]
  |            ^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `runtime` due to previous error

**Build in nightly:**
(base) H:\deno_tauri>rustup run nightly cargo build
   Compiling ring v0.16.20
   Compiling libffi v2.0.1
   Compiling rusqlite v0.25.4
error: no rules expected the token `aarch64_apple`
   --> C:\Users\tony_\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.20\src\cpu.rs:257:13
    |
165 |     macro_rules! features {
    |     --------------------- when calling this macro
...
257 |             aarch64_apple: true,
    |             ^^^^^^^^^^^^^ no rules expected this token in macro call

error[E0425]: cannot find value `AES` in module `cpu::arm`
   --> C:\Users\tony_\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.20\src\aead\aes.rs:381:65
    |
381 |         if cpu::intel::AES.available(cpu_features) || cpu::arm::AES.available(cpu_features) {
    |                                                                 ^^^ not found in `cpu::arm`
    |
help: consider importing this constant
    |
15  | use crate::cpu::intel::AES;
    |

error[E0425]: cannot find value `PMULL` in module `cpu::arm`
   --> C:\Users\tony_\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.20\src\aead\gcm.rs:315:26
    |
315 |             || cpu::arm::PMULL.available(cpu_features)
    |                          ^^^^^ not found in `cpu::arm`

error[E0425]: cannot find value `ARMCAP_STATIC` in this scope
   --> C:\Users\tony_\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\ring-0.16.20\src\cpu.rs:235:41
    |
235 |             if self.mask == self.mask & ARMCAP_STATIC {
    |                                         ^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `ring` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by marc2332** [comment]
Hey! `deno_tauri` has been finally moved to https://github.com/astrodon/astrodon/tree/feature/deno_tauri , if you want to try it, you can try running https://github.com/marc2332/deno_code_runner :D

**Comment by marc2332** [comment]
Okay, this actually happened to me too https://github.com/marc2332/astrodon/runs/5679738922?check_suite_focus=true 🤔
